  dataset_path: "Dataset/Games_v1_timed/games_timed_test_one.pt"
  checkpoint_dir: "ModelSource/Checkpoints"
  out_dir: "Results/Games_v1_timed"
  batch_size: 64
  num_workers: 4
  hidden_dim: 128
  num_layers: 6
  lambda_decay: 0.9
  mate_loss_weight: 0.5
  num_mate_classes: 10
  max_depth: 10